{% set name = "conda-bonjour" %}{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BolunDai0216/conda-bonjour/archive/v0.0.3.tar.gz
  sha256: 8c18017f9a43d77bcc35165437546eac44d06d16af79bd2fc47c91f054bed98f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - pybind11 >=2.10.0
    - cmake
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.26.4

test:
  imports:
    - conda_bonjour
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BolunDai0216/conda-bonjour
  summary: Tutorial on publishing to Conda
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BolunDai0216
