{% set name = "conda-bonjour" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BolunDai0216/conda-bonjour/archive/v{{ version }}.tar.gz
  sha256: 5be2d53028c1d617d8d4a05430170abe677b7f99192f8769d4714f8805057881

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - eigen
    - cmake
    - wheel
    - ninja
    - pip
  host:
    - python ==3.10
    - setuptools >=61.0.0
    - pybind11 >=2.10.0
    - cmake
    - wheel
    - ninja
    - pip
    - eigen
  run:
    - python ==3.10
    - numpy >=1.22.0

test:
  imports:
    - conda_bonjour
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Tutorial on publishing to Conda
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BolunDai0216
